### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Authentication 2.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/authentication#105]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse Glassfish 6.0.0-M3-2020-10-04](https://github.com/eclipse-ee4j/glassfish/releases/download/6.0.0-M3-2020-10-04/glassfish-6.0.0-M3-2020-10-04.zip)
- [x] Specification Name, Version and download URL
  [Jakarta Authentication 2.0](https://jakarta.ee/specifications/authentication/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  Promoted: [Jakarta Authentication TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-authentication-tck-2.0.0.zip)
  Final: [Jakarta Authentication TCK 2.0.0](https://download.eclipse.org/jakartaee/authentication/2.0/eclipse-authentication-tck-2.0.0.zip), SHA-256: 4fff0e3984cec6937db1e5b2e1894534f695fe72ad3aeb076a8423fa5845ad07
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-authentication/2.0/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Please add link to [promoted TCK](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-authentication-tck-2.0.0.zip), so reviewers can verify it properly.
Also, please update the [TCK Summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-authentication/2.0/TCK-Results.html) to use the same **promoted** zip (so it won't be inadvertently made stale later if the staged folder is removed from the downloads).

**Comment by arjantijms** [comment]
PR to update TCK summary: https://github.com/eclipse-ee4j/glassfish/pull/23247

**Comment by arjantijms** [comment]
As project lead I assert this can be marked accepted and closed.
