### ISSUE TITLE
Specification text still mentions required compatibility with Java 1.4

### ISSUE THREAD

**Issue by rdebusscher** [eclipse-ee4j/authentication#98]
For Jakarta EE 9, the minimum JDK version is set to 1.8. Which is also mentioned in the readme file and defined in the pom.xml.

**Comment by arjantijms** [comment]
True, I'll remove that, thx! 

Note that technically the API is still at 1.4. I started the discussion about brining in generics, but that appeared to be too complex for the 2.0.0 release (Jakarta EE 9)
